# USAGE: python main.py --options options/dsads_flex.yaml

# Data

data_set: dsads_flex
data_path: /home/arw27/CS4099/dytox-har/har/DSADS/dsads.mat

features: 405
embed_dim: 768
patch_size: 64

num_classes: 152
base_increment: 12
increment: 10

# Training

batch_size: 32
n_epochs: 500

# Rehearsal 
rehearsal_samples: 20

# Optimiser

optimiser: SGD
learning_rate: 0.01
weight_decay: 0.0001
momentum: 0.9

# Saving

save_model: true
save_dir: saves