# python ../../har_expert_trainer.py -d 1 -lr 0.01 -wd 1e-4 -mom 0 -b 20 
# -e 50 -sch 50 -exemplar_per_class 10 -gmm 1 -hidden_size 50 
# -save_path 'trial/dsads_e50_50_1.pkl' > 'trial/dsads_e50_50_1.txt'

# USAGE: python /home/arw27/CS4099/dmoe/main.py --options options/dsads.yaml

data_set: dsads
data_path: /home/arw27/CS4099/dmoe/har/DSADS/dsads.mat

batch_size: 32
n_epochs: 100

features: 405
patch_size: 45

num_classes: 19
base_increment: 3
increment: 2

save_dir: saves
save_model: true