# USAGE: python /home/arw27/CS4099/dmoe/main.py --options options/dsads.yaml

# Data

data_set: dsads
data_path: /home/arw27/CS4099/dmoe/har/DSADS/dsads.mat

features: 405
patch_size: 45

num_classes: 19
base_increment: 3
increment: 2

# Training

batch_size: 32
n_epochs: 200

# Optimiser

optimiser: SGD
learning_rate: 0.01
weight_decay: 0.0001
momentum: 0.9

# Saving

save_model: true
save_dir: saves