# USAGE: python /home/arw27/CS4099/dmoe/main.py --options options/pamap.yaml

# Data

data_set: hapt
data_path: /home/arw27/CS4099/dmoe/har/HAPT

features: 561
embed_dim: 768
patch_size: 64

num_classes: 12
base_increment: 2
increment: 2

# Training

batch_size: 32
n_epochs: 500

# Optimiser

optimiser: SGD
learning_rate: 0.01
weight_decay: 0.0001
momentum: 0.9

# Saving

save_model: false
save_dir: saves