# USAGE: python main.py --options options/hapt.yaml

# Data
data_set: hapt
data_path: /home/arw27/CS4099/dytox-har/har/HAPT

features: 561
embed_dim: 768
patch_size: 64

num_classes: 12
base_increment: 2
increment: 2

# Training
batch_size: 32
n_epochs: 500

early_stopping: true
patience: 50
min_delta: 0
restore_best_weights: true

# Rehearsal
rehearsal: GaussianMixtureModel
rehearsal_samples_per_class: 50

# Optimiser
optimiser: SGD
learning_rate: 0.01
weight_decay: 0.0001
momentum: 0.9

# Saving
save_dir: saves