# USAGE: python main.py --options options/wisdm_flex.yaml

# Data

data_set: wisdm_flex
data_path: /home/arw27/CS4099/dytox-har/har/WISDM/dataset/arff_files/phone/accel/all.csv

features: 91
embed_dim: 768
patch_size: 48

num_classes: 894
base_increment: 34
increment: 20

# Training

batch_size: 128
n_epochs: 500

early_stopping: true
patience: 50
min_delta: 0
restore_best_weights: true

# Rehearsal 
rehearsal: GaussianMixtureModel
rehearsal_samples_per_class: 50

# Optimiser

optimiser: AdamW
learning_rate: 0.01
weight_decay: 0.0001
momentum: 0

# Saving

save_dir: saves